#!/bin/sh
sudo apt install qemu-utils
sudo apt install python3
sudo apt install python3-pip
sudo apt install graphviz libgraphviz-dev pkg-config && pip3 install pygraphviz
pip3 install pyangbind
pip3 install networkx
