#!/bin/bash

QCOW_IMAGE_NAME="japan_ntt"

QCOW_TEMPLATE_IMAGE="../templates/template-kvm-debian9-kernel4.9.0-13-amd64.qcow"

XEN_SPEC_LIST="../specs/japan_ntt/xen_con0.spec,../specs/japan_ntt/xen_pc1.spec,../specs/japan_ntt/xen_pc2.spec,../specs/japan_ntt/xen_pc3.spec,../specs/japan_ntt/xen_pc4.spec,../specs/japan_ntt/xen_pc5.spec,../specs/japan_ntt/xen_pc6.spec,../specs/japan_ntt/xen_pc7.spec,../specs/japan_ntt/xen_pc8.spec,../specs/japan_ntt/xen_pc9.spec,../specs/japan_ntt/xen_pc10.spec,../specs/japan_ntt/xen_pc11.spec,../specs/japan_ntt/xen_pc12.spec,../specs/japan_ntt/xen_router1.spec,../specs/japan_ntt/xen_router2.spec,../specs/japan_ntt/xen_router3.spec,../specs/japan_ntt/xen_router4.spec,../specs/japan_ntt/xen_router5.spec,../specs/japan_ntt/xen_router6.spec,../specs/japan_ntt/xen_router7.spec,../specs/japan_ntt/xen_router8.spec,../specs/japan_ntt/xen_router9.spec,../specs/japan_ntt/xen_router10.spec,../specs/japan_ntt/xen_router11.spec,../specs/japan_ntt/xen_router12.spec,../specs/japan_ntt/xen_router13.spec,../specs/japan_ntt/xen_router14.spec,../specs/japan_ntt/xen_router15.spec,../specs/japan_ntt/xen_router16.spec,../specs/japan_ntt/xen_router17.spec,../specs/japan_ntt/xen_router18.spec,../specs/japan_ntt/xen_router19.spec,../specs/japan_ntt/xen_router20.spec,../specs/japan_ntt/xen_router21.spec,../specs/japan_ntt/xen_router22.spec,../specs/japan_ntt/xen_router23.spec,../specs/japan_ntt/xen_router24.spec,../specs/japan_ntt/xen_router25.spec,../specs/japan_ntt/xen_router26.spec,../specs/japan_ntt/xen_router27.spec,../specs/japan_ntt/xen_router28.spec,../specs/japan_ntt/xen_router29.spec,../specs/japan_ntt/xen_router30.spec,../specs/japan_ntt/xen_router31.spec,../specs/japan_ntt/xen_router32.spec,../specs/japan_ntt/xen_router33.spec,../specs/japan_ntt/xen_router34.spec,../specs/japan_ntt/xen_router35.spec,../specs/japan_ntt/xen_router36.spec,../specs/japan_ntt/xen_router37.spec,../specs/japan_ntt/xen_router38.spec,../specs/japan_ntt/xen_router39.spec,../specs/japan_ntt/xen_router40.spec,../specs/japan_ntt/xen_router41.spec,../specs/japan_ntt/xen_router42.spec,../specs/japan_ntt/xen_router43.spec,../specs/japan_ntt/xen_router44.spec,../specs/japan_ntt/xen_router45.spec,../specs/japan_ntt/xen_router46.spec,../specs/japan_ntt/xen_router47.spec,../specs/japan_ntt/xen_router48.spec,../specs/japan_ntt/xen_router49.spec,../specs/japan_ntt/xen_router50.spec,../specs/japan_ntt/xen_router51.spec,../specs/japan_ntt/xen_router52.spec,../specs/japan_ntt/xen_router53.spec,../specs/japan_ntt/xen_router54.spec,../specs/japan_ntt/xen_router55.spec"

QCOW_TAR_LIST=""
